# Run AFTER build.py:  python3 build.py && python3 enrich.py   (OUT = /home/claude/site)
import re,glob,os
OUT="/home/claude/site";UPD="October 2, 2026"
def rd(f):return open(f"{OUT}/{f}",encoding="utf-8").read()
def wr(f,s):open(f"{OUT}/{f}","w",encoding="utf-8").write(s)
def L(u,t):return f'<li><a href="{u}" rel="noopener" target="_blank">{t}</a></li>'
SRC={
"roi":[L("https://nces.ed.gov/collegenavigator/","NCES College Navigator"),L("https://studentaid.gov/","Federal Student Aid"),L("https://www.bls.gov/ooh/","BLS Occupational Outlook Handbook"),L("https://research.collegeboard.org/trends/college-pricing","College Board: Trends in College Pricing")],
"universities":[L("https://www.topuniversities.com/world-university-rankings","QS World University Rankings"),L("https://www.timeshighereducation.com/world-university-rankings","Times Higher Education Rankings"),L("https://nces.ed.gov/collegenavigator/","NCES College Navigator"),L("https://www.ucas.com/","UCAS (UK admissions)")],
"careers":[L("https://www.bls.gov/ooh/","BLS Occupational Outlook Handbook"),L("https://www.naceweb.org/","NACE: Career readiness and internship research"),L("https://www.cfainstitute.org/","CFA Institute"),L("https://www.onetonline.org/","O*NET OnLine")]}
exec(open("expand.py",encoding="utf-8").read())
# ---- articles: byline, sources, schema
for f in glob.glob(f"{OUT}/article-*.html"):
    s=rd(os.path.basename(f));m=re.search(r'category-(\w+)\.html">',s);c=m.group(1) if m else "roi"
    s=re.sub(r'<p class="note">Wells Love Research Team · ([^<]*)</p>',lambda m:f'<p class="note">By <a href="author.html">wellslove.com</a> · Published {m.group(1).replace(" · "," · ")} · Last reviewed {UPD} · <a href="editorial-policy.html">How we write</a></p>',s,1)
    blk=f'<h2>Sources and further reading</h2><p>Figures and claims in this guide should be checked against primary sources. Start with:</p><ul>{"".join(SRC[c])}</ul><p class="note">Rankings, salaries and tuition change every year. Always confirm current numbers on the official site before making decisions. See our <a href="editorial-policy.html">editorial policy</a> or <a href="contact.html">report a correction</a>.</p>'
    k='<p class="note" style="margin-top:30px">';assert k in s;s=s.replace(k,EXP.get(os.path.basename(f)[8:-5],'')+blk+k,1)
    t=re.search(r'<h1[^>]*>(.*?)</h1>',s).group(1)
    ld='<script type="application/ld+json">{"@context":"https://schema.org","@type":"Article","headline":"%s","author":{"@type":"Organization","name":"wellslove.com","url":"https://wellslove.com/author.html"},"publisher":{"@type":"Organization","name":"Wells Love"},"dateModified":"2026-10-02"}</script>'%t.replace('"',"'")
    wr(os.path.basename(f),s.replace("</head>",ld+"</head>",1))
# ---- new pages via build.page
import builtins
def mk(fn,t,d,body):page(fn,t,d,f'<section class="section"><div class="wrap art"><p class="eyebrow">ABOUT WELLS LOVE</p><h1 style="font-size:36px;margin:8px 0 18px">{t}</h1>{body}</div></section>',"about.html")
mk("about.html","About Wells Love","Who runs Wells Love, what we publish, how our tools work and how we are funded.",f'''<p>Wells Love is an independent education and career resource for students and early-career professionals. We combine free browser-based tools with plain-language guides on choosing a university, understanding what a degree really costs, and building a first career in finance and technology.</p>
<h2>Why this site exists</h2><p>Choosing where to study, how to pay for it and how to present yourself to employers are some of the most expensive decisions young people make, and much of the advice online is either sales copy or buried in jargon. We build tools that let you test the numbers with your own figures, and we write guides that explain the reasoning so you can check it.</p>
<h2>What we publish</h2><ul><li><b>Tools:</b> a <a href="roi-calculator.html">College ROI Calculator</a>, a <a href="loan-calculator.html">Loan Calculator</a>, a <a href="resume-builder.html">CV Builder</a> and an <a href="ats-checker.html">ATS Resume Analyzer</a> that accepts PDF, Word or pasted text.</li><li><b>Guides:</b> university shortlists, career-path timelines and finance specializations. See the <a href="articles.html">article library</a>.</li></ul>
<h2>Who writes it</h2><p>Content is produced by the <a href="author.html">wellslove.com</a> and published under the standards in our <a href="editorial-policy.html">editorial policy</a>. The tools are designed and built in-house.</p>
<h2>Privacy by design</h2><p>The CV Builder and ATS Analyzer run in your browser. Resume files you upload are read on your device and are not sent to our servers. Details are in the <a href="privacy.html">Privacy Policy</a>.</p>
<h2>How we are funded</h2><p>The site is free to use. We may display advertising or earn from partner links, which never changes how we rank or describe a school, employer or product. See the <a href="advertiser.html">Advertiser Disclosure</a>.</p>
<h2>What we are not</h2><p>We are not a financial adviser, lawyer, admissions consultant or recruiter. Tool results are estimates for planning, not guarantees. Contact us at <a href="mailto:contact@wellslove.com">contact@wellslove.com</a> with questions or corrections.</p>''')
mk("author.html","wellslove.com","Meet the editorial team behind Wells Love guides and tools, and how we research and review our work.",f'''<p>Guides on Wells Love are written and reviewed by our editorial team, which covers higher education, personal finance and early-career recruiting for students and young professionals.</p>
<h2>Focus areas</h2><ul><li>University selection and admissions across the US, UK and Europe</li><li>College costs, student loans and return on investment</li><li>Internships, CVs, applicant tracking systems and entry-level finance careers</li></ul>
<h2>How a guide is produced</h2><ol><li>Pick a question students actually ask and define who the answer is for.</li><li>Gather facts from primary sources such as government statistics, university sites and official ranking publishers.</li><li>Write in plain language, state assumptions and mark editorial opinion as opinion.</li><li>Review, date and republish whenever figures change.</li></ol>
<h2>Corrections</h2><p>Found an error or outdated number? Write to <a href="mailto:contact@wellslove.com">contact@wellslove.com</a> with the page and the source. Verified corrections are made promptly and the review date is updated.</p>
<p><a href="editorial-policy.html">Read our editorial policy</a> · <a href="articles.html">Browse all articles</a></p>''')
mk("editorial-policy.html","Editorial Policy","How Wells Love researches, reviews, updates and corrects its guides, and how advertising is kept separate.",f'''<h2>Accuracy and sourcing</h2><p>Statistics and factual claims come from primary or authoritative sources, listed at the end of each guide. When we cite a ranking we name its publisher. Lists marked "editorial" are our own judgment, not a scored index.</p>
<h2>Independence</h2><p>Advertisers and partners do not influence which schools, employers or products we mention or how we describe them. Sponsored or affiliate links, if any, are disclosed.</p>
<h2>Updates</h2><p>Each guide shows when it was published and last reviewed. Tuition, rankings, salaries and policies change, so we revisit guides at least once a year.</p>
<h2>Tools and estimates</h2><p>Calculators and analyzers use simplified, documented assumptions. Results are estimates, not financial, legal or hiring advice.</p>
<h2>Corrections</h2><p>Send corrections to <a href="mailto:contact@wellslove.com">contact@wellslove.com</a>. We verify against the source, fix the page and update the review date.</p>''')
# ---- tool explainers
def add(fn,html):
    s=rd(fn);i=s.rfind("</div></section></main>");wr(fn,s[:i]+f'<div class="art" style="margin-top:36px">{html}</div>'+s[i:])
add("roi-calculator.html",'''<h2>How to use the ROI calculator well</h2><p>Enter the yearly cost of attendance (tuition, housing, books, fees), the number of years, and the gross salary you realistically expect after graduating. The tool returns total cost, a simplified net income and a payback period, the number of years of net earnings needed to equal what you spent.</p>
<h3>A worked example</h3><p>Say a four-year program costs $40,000 per year, so $160,000 in total, and the expected starting salary is $80,000. At the calculator's flat 75% net-income assumption that is $60,000 a year, and the payback period is about 2.7 years, which falls in the High band. Raise the cost to $70,000 per year with the same salary and payback rises to about 4.7 years, a Moderate result.</p>
<h3>What it leaves out</h3><ul><li><b>Scholarships and aid:</b> enter your net yearly cost after aid for a truer result.</li><li><b>Loan interest:</b> borrowing adds cost. Model it with the <a href="loan-calculator.html">Loan Calculator</a>.</li><li><b>Living costs and lost income:</b> the years you study are years you are not working full time.</li><li><b>Real taxes:</b> actual tax depends on country, state and income level.</li></ul>
<h3>Tips for realistic inputs</h3><p>Use salary data for your field and city from the <a href="https://www.bls.gov/ooh/" rel="noopener" target="_blank">BLS Occupational Outlook Handbook</a> or school outcome reports, not best-case offers. Run a low, middle and high salary scenario and compare. A program that only pays off in the best case is a risky choice.</p>
<h3>More questions</h3><p><b>Can I compare two schools?</b> Yes. Run each separately and compare the payback periods and total costs.</p><p><b>Is a shorter payback always better?</b> Not necessarily. Career satisfaction, growth and non-financial goals matter too. Use the number as one input.</p>''')
add("loan-calculator.html",'''<h2>How the loan calculator works</h2><p>Enter the amount borrowed, the annual interest rate and the term. The calculator spreads the balance over equal monthly payments using the standard amortization formula: payment = P × r ÷ (1 − (1 + r)<sup>−n</sup>), where P is the principal, r the monthly rate (annual rate ÷ 12) and n the number of monthly payments.</p>
<h3>A worked example</h3><p>Borrowing $30,000 at 6% over 10 years gives a payment of roughly $333 a month, about $40,000 repaid in total, so around $10,000 goes to interest. Stretching the same loan to 20 years cuts the payment to about $215 but raises total interest to roughly $21,600.</p>
<h3>Ways to pay less interest</h3><ul><li>Choose the shortest term you can comfortably afford.</li><li>Make extra payments toward principal when possible, after confirming there is no prepayment penalty.</li><li>Compare offers by APR and total cost, not only by the monthly payment.</li></ul>
<h3>Limits</h3><p>Results are estimates. Real loans may include fees, variable rates, grace periods or capitalized interest. Federal student loan terms are explained at <a href="https://studentaid.gov/" rel="noopener" target="_blank">Federal Student Aid</a>. This is not financial advice, so check your lender's disclosure before signing.</p>''')
add("ats-checker.html",'''<h2>Using the analyzer with your own CV</h2><p>Upload a PDF, Word (.docx) or TXT file, or paste the text. For the best read, use a text-based PDF exported from Word, Google Docs or another editor, not a scan or a photo. Add the target job title and the full job description to measure keyword match. The report shows what was extracted, so you can see how a machine reads your CV.</p>
<h3>What is an ATS?</h3><p>An applicant tracking system collects and filters applications. It parses your file into fields such as job titles, dates, employers, education and skills, and recruiters search and rank those fields. If parsing fails, your experience may not be searchable even if the document looks fine to a human.</p>
<h3>Common reasons CVs score low</h3><ul><li><b>Missing dates:</b> use a clear format such as "Jan 2021 - Present" for every role.</li><li><b>Non-standard headings:</b> use Experience, Education and Skills.</li><li><b>Vague bullets:</b> start with an action verb and add numbers (percentages, money, team size).</li><li><b>Keywords not matching the posting:</b> mirror the exact terms the employer uses where they are true for you.</li><li><b>Layouts that scramble text:</b> text boxes, tables, icons and heavy graphics can break parsing.</li></ul>
<h3>Frequently asked questions</h3><p><b>Is my CV stored?</b> No. The file is read in your browser and not uploaded to our servers.</p><p><b>Does a high score guarantee interviews?</b> No. Every employer's system is different and humans make the final decision. Treat the score as a checklist for fixing obvious problems.</p><p><b>Why was my two-column PDF read in a different order?</b> The analyzer detects columns and reads the main column first. Check the extracted text and edit it if needed.</p><p>Need a clean, ATS-friendly layout? Build one in the <a href="resume-builder.html">CV Builder</a>.</p>''')
